[package]
name = "intro_00"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
anyhow = "1.0.83"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0"
ticket_fields = { path = "../../../helpers/ticket_fields" }
